FROM node:18-alpine

WORKDIR /app

LABEL org.opencontainers.image.title="KMNR Website (Frontend)" \
      org.opencontainers.image.description="A student radio station run by Missouri S&T students" \
      org.opencontainers.image.version="2.1.0" \
      org.opencontainers.image.authors="Heptagon Solutions" \
      org.opencontainers.image.source="https://github.com/DJCubed12/New-KMNR-Website/"

# Copy just dependency info so docker can cache the npm installs
COPY frontend/package.json frontend/package-lock.json ./

RUN npm install -q -g @angular/cli@16.1.0
RUN npm install -q

COPY frontend .

EXPOSE 8080
EXPOSE 4200
EXPOSE 3000

CMD ["npm", "run", "start-docker"]
