FROM mariadb:lts

ENV MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1

LABEL org.opencontainers.image.title="KMNR Website (Database)" \
      org.opencontainers.image.description="A student radio station run by Missouri S&T students" \
      org.opencontainers.image.version="2.1.0" \
      org.opencontainers.image.authors="Heptagon Solutions" \
      org.opencontainers.image.source="https://github.com/DJCubed12/New-KMNR-Website/"

COPY backend/setup.sql /docker-entrypoint-initdb.d/
COPY backend/sample_data.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
