import { DayOfTheWeek } from 'src/models/general';
import { Show } from 'src/models/show';

export const DEMO_SCHEDULE: Show[] = [
  {
    id: 3416,
    name: 'One to Two Grooves',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 13,
    endTime: 14,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 718,
        djName: 'KMNonsense',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3348,
    name: 'Loony Tunes',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 12,
    endTime: 13,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 634,
        djName: 'Loony Juic3',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3349,
    name: 'On The Rocks',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 679,
        djName: 'MC Pebble',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3350,
    name: " Your Aunt's favorite Radio Show",
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 10,
    endTime: 11,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 716,
        djName: 'Kublai Khan',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3438,
    name: 'TBD',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 18,
    endTime: 19,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 695,
        djName: 'DJ bebop',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3351,
    name: 'Freaks and Greeks',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 0,
    endTime: 1,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 681,
        djName: 'Apollo',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3351,
    name: 'Freaks and Greeks',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 0,
    endTime: 1,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 687,
        djName: 'Neptune',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3337,
    name: 'The High Ground',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 23,
    endTime: 0,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 651,
        djName: 'MC Sprig',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3337,
    name: 'The High Ground',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 23,
    endTime: 0,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 706,
        djName: 'DJ Dozone',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3338,
    name: "Bufo's Bops",
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 22,
    endTime: 23,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 669,
        djName: 'DJ Bufo',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3339,
    name: 'One Wizard One Orb',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 21,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 697,
        djName: 'The Lich King',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3340,
    name: 'Stanky Legs and the Barrel',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 20,
    endTime: 21,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 715,
        djName: 'AydenTheBlank',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3340,
    name: 'Stanky Legs and the Barrel',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 20,
    endTime: 21,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 714,
        djName: 'The Lorax',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3340,
    name: 'Stanky Legs and the Barrel',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 20,
    endTime: 21,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 698,
        djName: 'MC Zilch',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3341,
    name: 'the bite of 89.7',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 19,
    endTime: 20,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 695,
        djName: 'DJ bebop',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3341,
    name: 'the bite of 89.7',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 19,
    endTime: 20,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 651,
        djName: 'MC Sprig',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3342,
    name: 'Holy Mackerel',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 18,
    endTime: 19,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 614,
        djName: 'MC Salmon',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3342,
    name: 'Holy Mackerel',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 18,
    endTime: 19,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 688,
        djName: 'oddGod',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3343,
    name: 'The demiGod',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 17,
    endTime: 18,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 688,
        djName: 'oddGod',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3344,
    name: 'New Music Show',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 15,
    endTime: 17,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 673,
        djName: 'SheunTheSage',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3345,
    name: 'TBD',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 14,
    endTime: 15,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 632,
        djName: 'CraigTheYounger',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3345,
    name: 'TBD',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 14,
    endTime: 15,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 607,
        djName: 'Red Delicious ',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3346,
    name: 'Lone Ranger',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 13,
    endTime: 14,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 642,
        djName: 'Ginger Juic3',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3414,
    name: 'Stavromula Beta',
    shortDesc: '',
    day: DayOfTheWeek.Sunday,
    startTime: 12,
    endTime: 13,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 700,
        djName: 'MrDrTrey',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3352,
    name: 'Skylines',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 14,
    endTime: 15,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 680,
        djName: 'MC Silk Sound',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3353,
    name: 'Dumb, Dimwit & Doofus',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 15,
    endTime: 16,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 710,
        djName: 'Mama Roach',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3353,
    name: 'Dumb, Dimwit & Doofus',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 15,
    endTime: 16,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 680,
        djName: 'MC Silk Sound',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3353,
    name: 'Dumb, Dimwit & Doofus',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 15,
    endTime: 16,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 663,
        djName: 'KMNaurdwaur',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3354,
    name: 'Ginger Snaps',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 16,
    endTime: 17,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 642,
        djName: 'Ginger Juic3',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3355,
    name: 'Digested',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 17,
    endTime: 18,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 648,
        djName: 'DJ Ray',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3356,
    name: 'Gone Fishing',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 18,
    endTime: 19,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 614,
        djName: 'MC Salmon',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3357,
    name: "Kickin' Rocks",
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 19,
    endTime: 20,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 712,
        djName: 'KodaRed ',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3358,
    name: 'Late Night Snack',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 20,
    endTime: 21,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 715,
        djName: 'AydenTheBlank',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3359,
    name: 'The Wizards of Ooo',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 21,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 596,
        djName: 'Abracadan',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3359,
    name: 'The Wizards of Ooo',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 21,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 669,
        djName: 'DJ Bufo',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3359,
    name: 'The Wizards of Ooo',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 21,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 697,
        djName: 'The Lich King',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3360,
    name: 'halogenic',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 22,
    endTime: 23,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 662,
        djName: 'mc seventeen',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3361,
    name: 'Miz Biz',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 23,
    endTime: 0,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 669,
        djName: 'DJ Bufo',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3361,
    name: 'Miz Biz',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 23,
    endTime: 0,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 642,
        djName: 'Ginger Juic3',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3362,
    name: 'The Lazy Mushroom with OldMan ToadStool',
    shortDesc: 'cool stuff idk how to explain you just have to be ',
    day: DayOfTheWeek.Tuesday,
    startTime: 0,
    endTime: 2,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 566,
        djName: 'DJ ToadStool',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3363,
    name: 'Sage & Co.',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 10,
    endTime: 11,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 673,
        djName: 'SheunTheSage',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3364,
    name: 'Fish & Chips',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 711,
        djName: 'MC Poisson',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3365,
    name: 'Rock and/or Roll',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 13,
    endTime: 14,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 694,
        djName: 'Alexander the OK',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3366,
    name: 'Dihedrals and Records',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 14,
    endTime: 15,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 632,
        djName: 'CraigTheYounger',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3367,
    name: 'W.O.S.U.P',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 15,
    endTime: 16,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 663,
        djName: 'KMNaurdwaur',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3368,
    name: 'Tunes with Neptune',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 16,
    endTime: 17,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 687,
        djName: 'Neptune',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3369,
    name: 'Checks over Stripes',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 17,
    endTime: 18,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 659,
        djName: 'THE PRODIG\u00ce\u00a8',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3370,
    name: 'Sifting through Stardust',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 18,
    endTime: 19,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 699,
        djName: 'Discovery',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3371,
    name: 'Riffs of Revelations',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 19,
    endTime: 20,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 702,
        djName: 'The Prophet',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3372,
    name: 'Family Show',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 20,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 629,
        djName: 'DJCubed',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3372,
    name: 'Family Show',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 20,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 717,
        djName: 'Guy Whimsy',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3372,
    name: 'Family Show',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 20,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 716,
        djName: 'Kublai Khan',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3372,
    name: 'Family Show',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 20,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 655,
        djName: 'DJ Tessallations',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3373,
    name: 'the veil',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 22,
    endTime: 23,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 655,
        djName: 'DJ Tessallations',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3374,
    name: 'Metamorphosis',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 23,
    endTime: 0,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 710,
        djName: 'Mama Roach',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3375,
    name: "It's All About the Pentiums",
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 0,
    endTime: 1,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 638,
        djName: 'Mr. PC',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3377,
    name: 'getting weirder!',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 10,
    endTime: 11,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 655,
        djName: 'DJ Tessallations',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3377,
    name: 'getting weirder!',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 10,
    endTime: 11,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 662,
        djName: 'mc seventeen',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3376,
    name: 'Couch Time',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 696,
        djName: 'Doctor Doctor',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3378,
    name: 'Dawg Days',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 12,
    endTime: 13,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 693,
        djName: 'Big Dawg',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3379,
    name: 'TBD',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 13,
    endTime: 14,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 697,
        djName: 'The Lich King',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3380,
    name: 'Wizard Business Incorporated',
    shortDesc: 'Metal and its punk adjacent genres, if you are luc',
    day: DayOfTheWeek.Wednesday,
    startTime: 14,
    endTime: 15,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 596,
        djName: 'Abracadan',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3381,
    name: 'The Parallaxing Pantomime',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 15,
    endTime: 16,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 703,
        djName: 'Jester Juic3',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3435,
    name: 'Engineering Hours',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 16,
    endTime: 18,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 589,
        djName: 'DJ Binary Swag',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3382,
    name: 'The Sanctum',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 20,
    endTime: 21,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 728,
        djName: 'Tim the Enchanter',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3383,
    name: 'The Jungle',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 21,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 704,
        djName: 'DJ Heffalump',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3384,
    name: 'Spoils of the Desert',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 22,
    endTime: 23,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 673,
        djName: 'SheunTheSage',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3385,
    name: 'Going Bananas',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 23,
    endTime: 0,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 676,
        djName: 'DJ Dart Monkey',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3386,
    name: 'Infomercial Block',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 0,
    endTime: 1,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 708,
        djName: 'Tron',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3386,
    name: 'Infomercial Block',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 0,
    endTime: 1,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 673,
        djName: 'SheunTheSage',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3387,
    name: 'SZP',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 10,
    endTime: 11,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 698,
        djName: 'MC Zilch',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3388,
    name: 'Caught in the Riptide',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 682,
        djName: 'MC Wave',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3436,
    name: 'music mode',
    shortDesc: '',
    day: DayOfTheWeek.Tuesday,
    startTime: 9,
    endTime: 10,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 671,
        djName: 'malamazo',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3389,
    name: 'Birds of a Feather',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 14,
    endTime: 15,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 677,
        djName: 'DJ Silly Goose',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3390,
    name: "Grandpa's Top Shelf",
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 15,
    endTime: 16,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 722,
        djName: 'Corn Juic3',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3391,
    name: 'Dr. odd & Mr. God',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 16,
    endTime: 17,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 688,
        djName: 'oddGod',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3393,
    name: 'Listening to the trees',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 19,
    endTime: 20,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 714,
        djName: 'The Lorax',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3394,
    name: 'One and One is Two',
    shortDesc: 'i want you... to listen',
    day: DayOfTheWeek.Thursday,
    startTime: 21,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [{ id: 674, djName: 'DGi', userName: 'John Doe', profileImg: null }],
  },
  {
    id: 3394,
    name: 'One and One is Two',
    shortDesc: 'i want you... to listen',
    day: DayOfTheWeek.Thursday,
    startTime: 21,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [{ id: 713, djName: 'DRo', userName: 'John Doe', profileImg: null }],
  },
  {
    id: 3395,
    name: 'On my own world',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 22,
    endTime: 0,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 672,
        djName: 'MC Spaced Out',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3396,
    name: 'That Time I Got Reincarnated as a DJ in Rolla MO',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 721,
        djName: 'MC Static',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3396,
    name: 'That Time I Got Reincarnated as a DJ in Rolla MO',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 590,
        djName: 'D. Stowater',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3396,
    name: 'That Time I Got Reincarnated as a DJ in Rolla MO',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 678,
        djName: 'Finnegan Lodes',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3396,
    name: 'That Time I Got Reincarnated as a DJ in Rolla MO',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 638,
        djName: 'Mr. PC',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3396,
    name: 'That Time I Got Reincarnated as a DJ in Rolla MO',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 670,
        djName: 'DJ Lamb Sauce',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3396,
    name: 'That Time I Got Reincarnated as a DJ in Rolla MO',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 644,
        djName: 'y2caveman',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3397,
    name: 'Yap Sesh',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 12,
    endTime: 13,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 634,
        djName: 'Loony Juic3',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3397,
    name: 'Yap Sesh',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 12,
    endTime: 13,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 682,
        djName: 'MC Wave',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3398,
    name: 'hooze cruise',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 13,
    endTime: 14,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 723,
        djName: 'The Hoose',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3399,
    name: 'Resonance',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 14,
    endTime: 15,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 705,
        djName: 'Benzene',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3400,
    name: 'Snapshot of Lucent Memoria',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 15,
    endTime: 16,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 575,
        djName: 'The Narrator',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3401,
    name: 'The Weather Report',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 16,
    endTime: 17,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 560,
        djName: 'MC Stratus',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3403,
    name: 'Sky Wave',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 18,
    endTime: 19,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 572,
        djName: 'MC Cirrus',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3404,
    name: 'The New Wave',
    shortDesc: '',
    day: DayOfTheWeek.Friday,
    startTime: 19,
    endTime: 20,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 721,
        djName: 'MC Static',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3405,
    name: 'Remember to Floss',
    shortDesc: 'Quality music only',
    day: DayOfTheWeek.Friday,
    startTime: 20,
    endTime: 21,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 719,
        djName: 'GOOP!',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3407,
    name: 'ii-V-I',
    shortDesc: '',
    day: DayOfTheWeek.Saturday,
    startTime: 11,
    endTime: 12,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 638,
        djName: 'Mr. PC',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3408,
    name: 'Tropical Rain Forest',
    shortDesc: '',
    day: DayOfTheWeek.Saturday,
    startTime: 12,
    endTime: 14,
    semester: { term: 'Fall', year: 2025 },
    hosts: [{ id: 674, djName: 'DGi', userName: 'John Doe', profileImg: null }],
  },
  {
    id: 3428,
    name: 'CraigTheElder',
    shortDesc: '',
    day: DayOfTheWeek.Saturday,
    startTime: 16,
    endTime: 17,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 632,
        djName: 'CraigTheYounger',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3429,
    name: 'Soul Resonance',
    shortDesc: '',
    day: DayOfTheWeek.Saturday,
    startTime: 18,
    endTime: 20,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 678,
        djName: 'Finnegan Lodes',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3411,
    name: 'Fury Road',
    shortDesc: '',
    day: DayOfTheWeek.Saturday,
    startTime: 20,
    endTime: 21,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 724,
        djName: 'Doctor Mad Max',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3412,
    name: 'Aqua Regia',
    shortDesc: 'different "theme" each week, you might enjoy this ',
    day: DayOfTheWeek.Saturday,
    startTime: 21,
    endTime: 22,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 720,
        djName: 'willow;arcanae',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3418,
    name: 'the great crupt',
    shortDesc: 'lorem ipsum\r\n\r\ngamblers deluxe uhh anypercent%chan',
    day: DayOfTheWeek.Friday,
    startTime: 0,
    endTime: 1,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 644,
        djName: 'y2caveman',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3430,
    name: 'Amateur Hour',
    shortDesc: '',
    day: DayOfTheWeek.Monday,
    startTime: 9,
    endTime: 10,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 618,
        djName: 'MC FRAF',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3420,
    name: 'Night Light',
    shortDesc: 'im kmnring it',
    day: DayOfTheWeek.Saturday,
    startTime: 22,
    endTime: 0,
    semester: { term: 'Fall', year: 2025 },
    hosts: [{ id: 713, djName: 'DRo', userName: 'John Doe', profileImg: null }],
  },
  {
    id: 3439,
    name: 'Intergalactic Backdrop',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 19,
    endTime: 20,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 699,
        djName: 'Discovery',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3425,
    name: 'Radio Redshift',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 20,
    endTime: 21,
    semester: { term: 'Fall', year: 2025 },
    hosts: [{ id: 674, djName: 'DGi', userName: 'John Doe', profileImg: null }],
  },
  {
    id: 3422,
    name: 'Gold Standard',
    shortDesc: 'I play super hot fire. Need I say more? Probably. ',
    day: DayOfTheWeek.Friday,
    startTime: 10,
    endTime: 11,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 717,
        djName: 'Guy Whimsy',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3434,
    name: 'Random Music Show',
    shortDesc: 'this show is soooo cool, all physical :}',
    day: DayOfTheWeek.Friday,
    startTime: 9,
    endTime: 10,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 716,
        djName: 'Kublai Khan',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3434,
    name: 'Random Music Show',
    shortDesc: 'this show is soooo cool, all physical :}',
    day: DayOfTheWeek.Friday,
    startTime: 9,
    endTime: 10,
    semester: { term: 'Fall', year: 2025 },
    hosts: [{ id: 713, djName: 'DRo', userName: 'John Doe', profileImg: null }],
  },
  {
    id: 3432,
    name: 'Mid-Century Melodrama',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 12,
    endTime: 13,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 595,
        djName: 'YozTheFoz',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3433,
    name: 'soundscapes',
    shortDesc: '',
    day: DayOfTheWeek.Thursday,
    startTime: 13,
    endTime: 14,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 664,
        djName: 'dj violet',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
  {
    id: 3437,
    name: 'Bananas & Broken Hearts',
    shortDesc: '',
    day: DayOfTheWeek.Wednesday,
    startTime: 9,
    endTime: 10,
    semester: { term: 'Fall', year: 2025 },
    hosts: [
      {
        id: 676,
        djName: 'DJ Dart Monkey',
        userName: 'John Doe',
        profileImg: null,
      },
    ],
  },
];
